name: dawnheumann
favicon: null
layout_spectrum: 0.75703
typography_spectrum: 0.92224
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#555555'
    - '#000000'
    - '#333333'
    - '#666666'
    - '#808080'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0.7606841379310936
  rhythmicContrast: 0.25
purpose: []
