name: dawnheumann
favicon: null
layout_spectrum: 0.00616
typography_spectrum: 0.92224
title: 'Dawn Heumann Photographer // Projects '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b0b0b0'
    - '#8a8a8a'
    - '#6b6b6b'
    - '#cacaca'
  brandStrength: 0.75
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
