name: dawnheumann
favicon: null
layout_spectrum: 0.00616
typography_spectrum: 0.92224
title: 'Dawn Heumann Photographer // Projects '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0e0c'
    - '#c8c5be'
    - '#728784'
    - '#f6f2ee'
    - '#9f5132'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
