name: dawnheumann
favicon: null
layout_spectrum: 0.9473343128338456
typography_spectrum: 0.5401066390331835
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.26539205107837915
  lightness: 0.9654923258349299
  saturation: 0.7606841379310936
  rhythmicContrast: 0.3467982036527246
purpose: []
