name: dawnheumann
favicon: null
layout_spectrum: 0.00616
typography_spectrum: 0.92224
title: 'Dawn Heumann Photographer // Projects '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfdfdf'
    - '#c1c1c1'
    - '#8c8c8c'
    - '#1f241e'
    - '#525252'
  brandStrength: 0.75
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
